### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RyanBram** [mmontag/chip-player-js#11]
Hi, @mmontag 😄 .
This is a very interesting and most feature complete javascript based music player.

I am really curious, what is license for this project as I cannot find any license notes here, except at every 3rd party player library project directory?

Thanks.

**Comment by mmontag** [comment]
Hi @RyanBram, I've added a GPLv3 license to the project. I believe this is necessary because some modules I've incorporated and made minor modifications to are licensed under GPL.

**Comment by RyanBram** [comment]
Hi @mmontag . Thanks for the answer.

As an indie developer, currently I need a javascript solution for my personal game to play module musics and MIDI. I found chiptune2.js and it is permisively licensed, but unfortunately  it doesn't updated yet and it doesn't support MIDI so I'll miss lots of latest HTML5 technologies and features (especially WASM for performance).

If you don't mind, can you re-consider about the "basic" license of your chip-player-js and only use GPLV3 if it is linked with GPL-ed code (I need only libxmp-lite and tinysoundfont for  Module music and MIDI music support which aren't GPL-ed).

Regards.

**Comment by mmontag** [comment]
Aha, I see. I will reconsider, need to do some bookkeeping on the whole license situation. 
If you are just picking and choosing elements, I'm happy with MIT license for my own code. 
Curious to see your project.

**Comment by mmontag** [comment]
I added a licensing section to the README and MIT license to my own code under src/.

**Comment by RyanBram** [comment]
Thank you very much @mmontag for your consideration.

I think the license issue is clear now. I have one more questions that hooefully can be answered by you in another issue.

Best regards,
RyanBram
