### ISSUE TITLE
Import files

### ISSUE THREAD

**Issue by EGA-man** [mmontag/chip-player-js#112]
It's cool to have all the music in Chip Player JS available, but there's just some tunes that won't be able to be played.  That's why I think it should have an option to import files like .nsf, .mid, .spc, .sf2, all that jazz.

**Comment by mmontag** [comment]
you can drag and drop files from your computer to play them as needed (even .sf2 now). 
Or do you want Chip Player to remember your local files somehow?

**Comment by polygonnedpotato** [comment]
> Or do you want Chip Player to remember your local files somehow?

implementing this through either firebase or IndexedDB would actually be a great idea and a great timesaver.

**Comment by jadasse** [comment]
> > Or do you want Chip Player to remember your local files somehow?
> 
> implementing this through either firebase or IndexedDB would actually be a great idea and a great timesaver.

yea

**Comment by mmontag** [comment]
Sounds like a cool idea, hopefully I can do this soon. 
BTW, what are these cool files that I'm missing from the catalog? 🙂

**Comment by jadasse** [comment]
> Sounds like a cool idea, hopefully I can do this soon. 
> 
> BTW, what are these cool files that I'm missing from the catalog? 🙂 

I think he means files from local drives, not coming with the catalog.

**Comment by jadasse** [comment]
Also, can it be added as a button prompt? Apparently, drag-and-drop doesn't work in some cases.

**Comment by GunGunGun** [comment]
> Sounds like a cool idea, hopefully I can do this soon. BTW, what are these cool files that I'm missing from the catalog? 🙂

A lot honestly, the world of midi is vast, try some godtier RPG music from https://d-symphony.com/mt_00.html.

Also, the drag & drop feature can only add 1 music at a time, even if I drag 100 midi files Chip Player only plays the 1st song and ignore that rest, would be great if that can be improved.

**Comment by mmontag** [comment]
Thanks @GunGunGun, these are really cool.
I am always interested to find collections of curated MIDI music in case you know of more like this. 

The issue with dragging multiple files is that it will need new UI to display the list. Maybe another tab for Local/Imported files. 
It might not be possible to create a folder structure there.

**Comment by mmontag** [comment]
I'm going to close this one, so if you spot some bugs please file a new issue!

**Comment by GunGunGun** [comment]
> Hey all, I added a Local Files tab - Chip Player JS will now keep track of local files you dragged, using the IndexedDB (via Emscripten filesystem API).
> 
> You can drag multiple files at once - if some of them are not song files, they will be ignored.
> 
> Behavior has changed slightly; the song won't play immediately when you drag a file. You have to click on it. It will be added to the bottom of the Local Files list.
> 
> @jadasse I will try to add a button prompt here too, but if you can post some details about which browser/platform doesn't work with drag & drop, that would be awesome.

Great job, this is such a huge quality of life, I'll definitely test and report if there's errors!
