### ISSUE TITLE
Add download links to the UI

### ISSUE THREAD

**Issue by jtsiomb** [mmontag/chip-player-js#115]
It would be really nice to provide download links somewhere in the UI, so when someone finds a song they like, they can easily grab it and save it locally. Even better if "folders" have download links too, to zip and download the whole thing in one go.

**Comment by mmontag** [comment]
It's in there, although a bit hidden - you can right click on any song and "Save As".

**Comment by jtsiomb** [comment]
The only save option I get is the browser's built in "save link as ..." which saves an html page. Tried it with both firefox (98.0) and chromium (100.0.4896.75).

![firefox](https://user-images.githubusercontent.com/2028446/175284110-089e2d80-6f1b-410b-9d27-194dafe33a79.png)
![chromium](https://user-images.githubusercontent.com/2028446/175284126-35320f46-209a-4141-998c-317bf8c943ff.png)

**Comment by mmontag** [comment]
Hey! Sorry for the late reply, but this was an oversight on my part. It was working for Search and Favorites, but not Browse.
Will be fixed in the next deploy!
