### ISSUE TITLE
Please add the ability to download MIDIs,

### ISSUE THREAD

**Issue by juanroman74454811** [mmontag/chip-player-js#119]
please

**Comment by skeddles** [comment]
any format. they should all be downloadable.

**Comment by juanroman74454811** [comment]
what is wrong with the ugly font, the () is
                                                          (
                                                          )

**Comment by mmontag** [comment]
The files are all downloadable if you right-click on the file in the Browse tab, and "Save As..."
I can add a simple download button since this might not be very obvious.

**Comment by skeddles** [comment]
ah, if that's the case i think it should also work on the name at the bottom for the current song. though i do think a separate download button would be best.

**Comment by mmontag** [comment]
Added a download button to the footer, next to song title. 💾 
![image](https://user-images.githubusercontent.com/946117/208777092-bee73d63-9f02-4fac-9d46-8d71ef440ed7.png)

**Comment by skeddles** [comment]
epic
