### ISSUE TITLE
All Super Mario 64 .miniusf files broken

### ISSUE THREAD

**Issue by applecuckoo** [mmontag/chip-player-js#121]
On the website, if you try playing the .miniusf files in `/Nintendo 64/Super Mario 64 (1996)(Nintendo EAD)(Nintendo)`, the files are all broken and they don't play. Running on Chrome 105 on macOS Monterey 12.5.1.

**Comment by mmontag** [comment]
Thanks, I accidentally deployed a bad build, will be fixed soon in next deploy.

**Comment by applecuckoo** [comment]
Cool, feel free to close the issue whenever that happens - thanks for the quick reply!

**Comment by mmontag** [comment]
Should be fixed now. Thanks!

**Comment by applecuckoo** [comment]
Can confirm the issue is fixed!
