### ISSUE TITLE
Demo songs from Yamaha

### ISSUE THREAD

**Issue by PoneyClairDeLune** [mmontag/chip-player-js#129]
Answering request at https://www.vogons.org/viewtopic.php?t=69307 .

The files are available under [octavia@ltgcgo/test/demo](https://github.com/ltgcgo/octavia/tree/main/test/demo), specifically `TheMusithm.mid` (MU50), `OutOfTheMuse.mid` (MU80), `ninety_hipty.mid` (MU90), `MU100DEMO.mid` (MU100), `PhoenixA.mid` (MU1000/2000) and `PhoenixB.mid` (MU1000/2000). Credits are also [available](https://github.com/ltgcgo/octavia/blob/main/CREDITS.md).

Demo songs from MU128 and the remaining one from MU2000 might also become available.

**Comment by mmontag** [comment]
Thanks! I've added these to the pending catalog updates.
