### ISSUE TITLE
Option to remove panning?

### ISSUE THREAD

**Issue by jadasse** [mmontag/chip-player-js#133]
Can Chip Player JS give the option to remove the panning of channels? For instance, NSF playback hard pans both pulse waves to stereo from mono. In my opinion, that can be a bit distracting.

**Comment by mmontag** [comment]
I added stereo width to GMEPlayer (NSF, SPC, VGM, etc.) settings (and moved settings out of the footer to give it more space). Try it out and let me know if this works for you.

**Comment by jadasse** [comment]
> I added stereo width to GMEPlayer (NSF, SPC, VGM, etc.) settings (and moved settings out of the footer to give it more space). Try it out and let me know if this works for you.

Works great
