### ISSUE TITLE
tuning issue when playing a .mod

### ISSUE THREAD

**Issue by smoothdeveloper** [mmontag/chip-player-js#140]
I noticed this module doesn't play right in the chiptune.app online player (assuming it uses this library):

https://gifx.co/music/Modland/Dalezy/arpeggiotisiert.mod

Checking in VLC or OpenMPT, it plays this file with correct tuning.

**Comment by zaphod77** [comment]
While it could be a fault in the player itself, it could also be a failure of "which tracker program made this module" autodetect.  

Notably, fasttracker and protracker both use .mod as the extension, yet are not compatible with each other!  A mod with a protracker style true bpm will slow to a crawl in fasttracker, while run the gauntlet horribly messes up in protracker, but is fine in fasttracker.  many mod players have a protracker compat toggle for exactly this purpose.

**Comment by mmontag** [comment]
I am going to close as this is a libxmp issue. Might be fixed if I update libxmp to latest version. 
Updated the list at #49 Problematic songs.
