### ISSUE TITLE
request: developer who can help me ...

### ISSUE THREAD

**Issue by ghost** [mmontag/chip-player-js#141]
Hi

Can I ask something?
I'm an autistic girl and I'm desperately looking for a developer who can make my dream come true: VGM support in the program Mixxx

http://www.mixxx.org

If you're curious, please read my request here! Click there on the github link to mixxx for details

https://github.com/ValleyBell/libvgm/issues/116

Thx so much!!!

**Comment by mmontag** [comment]
I wish you luck with your quest... but I'll close this issue for now. I don't have time to contribute to Mixxx
