### ISSUE TITLE
Sega Genesis: can't mute all channels

### ISSUE THREAD

**Issue by binary1230** [mmontag/chip-player-js#143]
Minor thing,

Example track:
https://chiptune.app/?play=Sega%20Genesis%2FSonic%20the%20Hedgehog%203%2F04%20-%20Angel%20Island%20Zone%20Act%202.vgz

If I uncheck all boxes one by one (without ALT+CLICKing)
![image](https://github.com/mmontag/chip-player-js/assets/5413064/d388c2f4-4c26-4d0b-a724-aac1d07d1bcc)

expected: all audio is muted
actual: I still hear the Snare drum even though all channels are unchecked.

If I then ALT+CLICK a channel to solo it, then uncheck that channel (showing all channels unchecked again), then the snare goes away.

If I then manually check each channel again one by one and turn them all back on, 
expected: all channels are back
actual: everything is back except the Snare is still missing

---
I suspect what's up is, the channel for the Genesis **DAC** channel is probably just not being exposed as a checkbox to the UI, or incorrectly?  

Also I notice (maybe) that the channel labelled "FM 6" never seems to be playing anything on the couple Genesis games I looked at when I solo'd it. Could this be related or like a mislabeled channel?

It explains the "solo" feature being able to mute all channels successfully too

https://youtu.be/F6n9aWEeI1s?t=247
^ vid showing all the channels

JS debugger shows:
SEGA PSG: 4 voices 
YM2612: 6 voices

the DAC channel is on the YM2612

I'll try and track it down a bit more

**Comment by mmontag** [comment]
Thanks for the report, I think I found the issue with this. [YM2612](https://github.com/mmontag/chip-player-js/blob/master/libvgm/player/player_wrapper.cpp#L73) should have 7 voices https://github.com/mmontag/chip-player-js/blob/master/libvgm/emu/cores/ym2612.c#L2483

**Comment by mmontag** [comment]
Also, to answer your question about no sound on FM6 (which I also wondered myself): according to wikipedia, the sixth channel of the YM2612 "can act as a basic PCM channel by means of the 'DAC Enable' register, disabling FM output for that channel but allowing it to play 8-bit pulse-code modulation sound samples." So it can either play PCM or FM, not both.
In libvgm and Chip Player JS, this will manifest as two distinct channels.

**Comment by binary1230** [comment]
Ah! Very fun, thanks much! That's awesome
