### ISSUE TITLE
MUS Support

### ISSUE THREAD

**Issue by GunGunGun** [mmontag/chip-player-js#160]
Like MIDI, MUS is another format for music composing, you can download and try some of them here: https://ichigos.com/sheets/510

JS MUS2MIDI: https://github.com/gareththegeek/mus2midi

I think MUS is even closer to chiptune than MIDI, because MUS is the format of Doom: https://www.doomworld.com/files/file/10676-doom-mus-player-v099a/

**Comment by mmontag** [comment]
Hi, thanks for the idea.
However, if MUS can be converted to MIDI without loss, as seems to be the case [1], it is unlikely that I would add support for MUS.  Other formats present a similar ambiguity, .S98 and .DRO (Dosbox Raw OPL) [2] for example. It makes more sense (for me to just convert them to the more capable .VGM.

[1] https://doomwiki.org/wiki/MUS
[2] https://moddingwiki.shikadi.net/wiki/DRO_Format

**Comment by GunGunGun** [comment]
> It makes more sense (for me to just convert them to the more capable

Yeah, I mean just being able to convert to MIDI and play is pretty good already, less work = better.
