### ISSUE TITLE
Incorrect duplicate song

### ISSUE THREAD

**Issue by JarrettBillingsley** [mmontag/chip-player-js#162]
`/Contemporary/Virt (Jake Kaufman)/Shovel Knight Dig OST/02. Overground (Main Layer).vgm` is incorrectly a duplicate of track 01. Weirdly the filesize is different but it sounds the same. 

I think there was briefly a copy of this directory that did actually have the correct version of this song, but the copy directory was deleted.

**Comment by mmontag** [comment]
Thanks, fixed
