### ISSUE TITLE
Firebase login not working on iOS 18.1

### ISSUE THREAD

**Issue by MikeMayer** [mmontag/chip-player-js#164]
May be unrelated to iOS 18.1 specifically but I have not encountered any sort of failure to login before or on any other browser I've tried. (Windows Chrome, macOS Safari)

Reproduction
- On a signed out browser, tap Login/Sign Up
- Observe new tab opening to Firebase with "The requested action is invalid."

https://github.com/user-attachments/assets/130e001d-75e1-49c5-8cf3-30bd1c844e61

**Comment by mmontag** [comment]
I updated to iOS 18 and was unable to reproduce this. Do you still have this problem?

**Comment by MikeMayer** [comment]
I still see a failure but the error message is different today(?) and lets me authenticate with Google. So it's marginally improved in that authN with the Google idp is kinda working.

iOS 18.1 (22B82)

I've tried on WiFi and on cellular as well as disabling any content blockers or privacy protections that have been problematic before.

I didn't need to do anything like that before when it was working in recent memory.

```
Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared. Some specific scenarios are - 1) Using IDP-Initiated SAML SSO. 2) Using signInWithRedirect in a storage-partitioned browser environment.
```

**Comment by MikeMayer** [comment]
Actually after refreshing the website and despite that error I am signed in. So, I guess it's okay but unclear to me how it worked in the end.

Feel free to close this issue.
