### ISSUE TITLE
Favourite saving doesn't appear to work

### ISSUE THREAD

**Issue by JakeWorrell** [mmontag/chip-player-js#24]
Hi
When I attempt to save a song as favourite the little heart icon goes yellow for a second and then reverts back to its original colour. Nothing can be found under the favourites tab.

Naturally, I am logged in.

Here's my user agent string in case that is useful: Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by mmontag** [comment]
Thanks! Somehow I completely broke favorites for new accounts. 😞

**Comment by mmontag** [comment]
Should be fixed now. Try logging in again!

**Comment by JakeWorrell** [comment]
Thanks, working great now! :)
