### ISSUE TITLE
More PC game music

### ISSUE THREAD

**Issue by JakeWorrell** [mmontag/chip-player-js#26]
I don't know how you would achieve this, but I would like to be able to listen to a few more PC game music tracks e.g:

- Transport Tycoon
- Theme Hospital
- Normality / Normality Inc

**Comment by mmontag** [comment]
Hi Jake, over the past year I've added a ton of PC game music, including the three you mentioned. Check the Game MIDI and Game Mods folders.

**Comment by JakeWorrell** [comment]
Awesome @mmontag, I'll be listening to some PC game music while I work! Thanks!
