### ISSUE TITLE
Player appears for a brief moment before disappearing

### ISSUE THREAD

**Issue by Titanic4** [mmontag/chip-player-js#39]
When I try to open the player it simply disappears shortly during loading process. Once that happens the "Error initializing constant Q transform." error pops up in the developer console. 
![Zrzut ekranu (44)](https://user-images.githubusercontent.com/1963921/83851108-2fb71900-a712-11ea-942a-88c3c52ca0e3.png)

This screenshot is made while Chrome is in Incognito Mode to rule out adblock extensions interfering with site's functionality.

Chrome version: 83.0.4103.97 64-bit

**Comment by mmontag** [comment]
Woah. This might be related to your high sample rate (192kHz). I'll have to look into it!

**Comment by thatsprettygood** [comment]
I'm at 96kHz and MIDI Playback is much faster than it should be.

**Comment by Titanic4** [comment]
@thatsprettygood I've checked with 8kHz sampling rate and the playback goes much slower than usual. I think the playback speed is governed by default playback device's sampling rate, since I've got perfect speed at 44.1 kHz sampling rate.

**Comment by mmontag** [comment]
Interesting, thanks for reporting. I've reproduced this locally; the pitch stays accurate, but the tempo changes with the sample rate.

**Comment by mmontag** [comment]
Separate issue for MIDI playback rate: #41

**Comment by mmontag** [comment]
Fixed this, and also fixed XMP support for high sample rates. (You should be able to play mod/s3m/xm/it files now.)
