### ISSUE TITLE
Yarn install error

### ISSUE THREAD

**Issue by gb-2312** [mmontag/chip-player-js#48]
I clone this repository successful, and `cd chip-player-js`, run bash-command `yarn install`, then console tips compile-failed, and output stack-error on console, and I found this error:

`node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v83-linux-x64-glibc.tar.gz `

How to resolve this? I'm not good at node.js, because node.js dependency is so complex...

System/Software Environment/Runtime:
```
[root@centos7-console chip-player-js]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

[root@centos7-console chip-player-js]# gcc --version

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@centos7-console chip-player-js]# npm -v
6.14.8
[root@centos7-console chip-player-js]# yarn -v
1.22.5

[root@centos7-console chip-player-js]# npm config get registry
https://registry.npmjs.org/
[root@centos7-console chip-player-js]# yarn config get registry
https://registry.yarnpkg.com
```
[yarn_install_error.log](https://github.com/mmontag/chip-player-js/files/5208599/yarn_install_error.log)

**Comment by mmontag** [comment]
Hm, that looks tricky... can you try starting over with npm instead of yarn? I should probably transition away from yarn.

**Comment by gb-2312** [comment]
> Hm, that looks tricky... can you try starting over with npm instead of yarn? I should probably transition away from yarn.

Wow, I have done it!!! Haha😄, it's to hard, thank you so much for your tips!🙏

I tried to downgrade the version of nodejs to v10.9.0, run bash-command `yarn install` again on macos, everything was done!

I encountered a little problem when compiling the sub-project, but in the end it was solved and successfully passed the compilation, and works fine!👍 I believe this is a great project!

![Screen Shot 2020-09-12 at 11 13 39 PM](https://user-images.githubusercontent.com/435219/92999081-ba4cb700-f550-11ea-928b-f458315fc12d.png)


My compile environment list:
```
macos: 10.15.6

node: v10.9.0
npm: 6.2.0
yarn: 1.22.5
emsdk: 1.38.45
m4: 1.4.17
autoconf: 2.69
automake: 1.16.2
libtool: 2.2.10

xcode: 11.7

compile libxmp:
#define HAVE_ROUND 1
```

**Comment by mmontag** [comment]
Nice work! Let me know if you have any suggestions to improve the documentation and portability of the project.
