### ISSUE TITLE
Arcade VGZ playback voice volume inconsistency issue

### ISSUE THREAD

**Issue by Titanic4** [mmontag/chip-player-js#50]
On certain VGZ files there's volume inconsistency. One of the prime examples is in Black Knight 2000 main theme. Notice how the vocals, as well as percussion are very quiet compared to the rest of available voices.
https://mmontag.github.io/chip-player-js/?q=black+kni&play=VGM+Rips%2FBlack_Knight_2000_(Williams_System_11B)%2F04+Main+Theme.vgz

Here's the video of the main theme BGM of this pinball machine. Notice how the percussion can be heard, as well as all the vocals. 
https://www.youtube.com/watch?v=p61YjWczwLM&t=17s

**Comment by mmontag** [comment]
Thanks for the report!
I will chalk this up to Game Music Emu not being as accurate as vgmplay/libvgm for the VGM format. 
It is on the roadmap to migrate eventually...I'll add these to the problematic songs list.
