### ISSUE TITLE
add repeat function

### ISSUE THREAD

**Issue by paperluigis** [mmontag/chip-player-js#51]
Please, add repeat function! _[ask for a function]_

Sometimes, I want to listen to music more than it's length.

**Comment by mmontag** [comment]
Many game songs were meant to repeat so I think this is even more important for a retro music player. 
It's on my list of things to do!

**Comment by paperluigis** [comment]
> Many game songs were meant to repeat so I think this is even more important for a retro music player.
> It's on my list of things to do!

Thanks! =)

**Comment by mankeli** [comment]
I definitely vote for this! What a great player and UI otherwise!

**Comment by mmontag** [comment]
Added a repeat button. It cycles through 3 modes (Repeat-All, Repeat-One, Off).

**Comment by mmontag** [comment]
Note that repeat-one mode won't repeat subtracks within NSF files. 
It's a Sequencer-level repeat, so it doesn't utilize loop points defined in song metadata.
Feel free to open another issue if that really bothers you :)

**Comment by mankeli** [comment]
NSF files are program code, any song length is defined afterwards. Game rips often play forever and so does most of the "scene" songs. This is also true for several other song formats. (SPC, SID, etc) Mod files also often rely on the "implicit" looping that the player just wraps to pattern 0 seamlessly, and there are also "jump to order" repeat commands in mod files.

I guess the repeat feature should use this if it's available?

**Comment by paperluigis** [comment]
Oh thank you!
I already knew songs could repeat, slowly watching how pattern 39 (for example) jumps back to pattern 5, excluding the start, making the length of song infinite.
