### ISSUE TITLE
Looping commands in modules cause playback bar to jump around

### ISSUE THREAD

**Issue by mankeli** [mmontag/chip-player-js#54]
For example at [05:00](https://mmontag.github.io/chip-player-js/browse/Game%20Mods?play=Game+Mods%2FTerminal+Velocity%2FDesert.mod) in this mod.

**Comment by mmontag** [comment]
I think this is a quirk of libxmp (underlying library).

It does not report a monotonically increasing playback position, but exposes only the raw xmp_frame_info.time https://github.com/libxmp/libxmp/blob/master/include/xmp.h#L326.
Similarly, I don't think the reported duration takes loops into account. It is only an estimate.
Would prefer not to patch libxmp, so this is how it will remain for now.

https://github.com/libxmp/libxmp/blob/f56472b117c592e3056a8d89aae847496df7dfac/docs/tracker_notes.txt#L218
