### ISSUE TITLE
Add an ability to drop .sf2 files

### ISSUE THREAD

**Issue by paperluigis** [mmontag/chip-player-js#78]
Basically an ability to load in custom soundfonts for MIDI files.
![image](https://user-images.githubusercontent.com/72666727/120954119-e3a91500-c767-11eb-828e-1ef741f2101a.png)

**Comment by mmontag** [comment]
This would be nice, especially for just trying stuff out.

In the long term, I am tempted to make a separate web MIDI player project with more room for features, and without the limitation of the DOS theme. With a nice piano roll visualizer and the ability to do MIDI routing per-channel.
