### ISSUE TITLE
Fix libADLMIDI banks

### ISSUE THREAD

**Issue by mmontag** [mmontag/chip-player-js#85]
Updating libADLMIDI at 39104089a30c696e174133830fd530678652c4cc reversed the bank reductions/custom OPL bank order that introduced in 92b7ab396a24a9c6ecd29fb599b6e58168b48380.

So now the default OPL3 bank is "AIL (Star Control 3...)". 
The default bank should be Win9x. It sounds similar but it's a bit louder.

- Level 1: change the default bank.
- Level 2: delete a bunch of banks.
- Level 3: use instructions in libADLMIDI/banks.ini to generate custom list of banks and add this to build process.

> ; If you want to change list of banks in libADLMIDI, just run
> ; "bin/gen_adldata src/adldata.cpp" and wait until it will generate updated
> ; banks store, and then run "make" to rebuild libADLMIDI library with new set of
> ; banks

**Comment by Wohlstand** [comment]
About the default bank number, it's always defined by the user side (for example, I keep the default bank number at the MixerX itself, setting the bank 58 after loading the thing)

P.S. Seems a good idea to add the CMake option to specify the custom path to the custom `banks.ini`, and make it use the custom-generated inst-db.cpp instead of default one.

**Comment by mmontag** [comment]
Yes, that way we can avoid tracked changes in the repo 👍

**Comment by Wohlstand** [comment]
Alternatively, you can disable embedded banks use at all, and make your own list of banks using WOPL banks (every bank can be saved in WOPL format using OPL3-BE), and passing via `adl_loadBankData()` call. This also will save your compile-time, and you are also able to add different banks in WOPL format at any moment having to don't re-generate the entire cache.

**Comment by Wohlstand** [comment]
>  The default bank should be Win9x. It sounds similar but it's a bit louder.

Because bank 0 uses the AIL volume model, the bank 58 uses the Win9x volume model, they are different volume scaling factors.

**Comment by mmontag** [comment]
I have put this issue to bed for now.

**Comment by Wohlstand** [comment]
> Do you have a list of which banks are nice and (more or less) GM-compatible?

Didn't it yet, but I would prepare a bunch of WOPL files for you that you can use at your side. Probably will try some tomorrow...
